### ISSUE TITLE
"Miami, FL" should technically be "Miami-Dade County, FL"

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/miami-budget#12]
In the sentence "We at Code for Miami have visualized Miami's 2016 budget proposal," don't forget that this is actually the county, not the city of Miami who has their own thing going on. So any thing specifically marked Miami should be Miami-Dade County for clarity.

**Comment by mugabits** [comment]
Fixed - http://miamigraph.com/
