### ISSUE TITLE
QA website in all device scenarios

### ISSUE THREAD

**Issue by maurop123** [Code-for-Miami/miami-budget#15]
The website and visual were designed for Chrome on Ubuntu. It needs to be looked at in all the different varieties to ensure ubiquitous usability.

Combinations include:
- Mac
  - Chrome
  - Firefox
  - Safari
- Windows
  - Chrome
  - Firefox
  - Safari
- Android
  - Chrome
- iOS
  - Chrome
  - Safari

If you review any of these combinations and find an issue or not, please leave a comment. That is how we'll track the completion of this ticket.

If there is a combination that you think should be supported that is not listed above, please comment.

**Comment by gargium** [comment]
I'd recommend the following combinations: 
- Windows: 
  - Internet Explorer 
- Windows Phone:
  - Internet Explorer

**Comment by gargium** [comment]
Test: Mac/Chrome
Results: 
1. Hitting "Data" nav button in top bar results in text being cut off. See screenshot: 
2. Clicking on profile pictures in "Team" section results in a shading effect, but no actual event or action. Not sure if thats intended/designed to be that way. Is clicking on a picture supposed to do anything?
![screen shot 2015-08-07 at 11 38 49 pm](https://cloud.githubusercontent.com/assets/7241365/9149414/a6768d9c-3d5d-11e5-90e5-62b6135baaa5.png)

**Comment by gargium** [comment]
Test: Mac/Safari
Results: 
1. Hitting "Data" nav button in top bar results in text being cut off. See screenshot for the Mac/Chrome test. 
2. Font of text beneath profile pictures in "Team" section toggles between heavy typeface and light typeface at an interval of every 2-ish seconds. See screenshots.

Ignore the seeming position offset. That was my mistake in taking the screenshot. Issue is within font. 
![screen shot 2015-08-07 at 11 50 59 pm](https://cloud.githubusercontent.com/assets/7241365/9149449/5011f3ae-3d5f-11e5-8e64-d3ef4215223a.png)
![screen shot 2015-08-07 at 11 50 51 pm](https://cloud.githubusercontent.com/assets/7241365/9149450/5013b234-3d5f-11e5-9b0e-26662541fe82.png)

**Comment by gargium** [comment]
Test: Mac/Firefox 
Results: 
1. Hitting "Data" nav button in top tab bar results in text being cut off. See screen shot from Mac/Chrome test. 
2. Hovering over various regions of the graph correctly populates the numbers but does not show a description or any text beneath the numbers. See screenshot: 
![screen shot 2015-08-07 at 11 58 53 pm](https://cloud.githubusercontent.com/assets/7241365/9149477/87091a30-3d60-11e5-8b11-74a20984c528.png)

**Comment by ErnieAtLYD** [comment]
I see this on my iPhone:

[image: IMG_0233.PNG]

**Comment by maurop123** [comment]
@ErnieAtLYD your image didn't make it through.

 @gargium thanks for the help! I'm making separate tickets of these issues you pointed out and closing this one.
