### ISSUE TITLE
Graph Engagement - Google Analytics

### ISSUE THREAD

**Issue by HiGregory** [Code-for-Miami/miami-budget#20]
We recently added a blog.miamigraph.com page which is great for content creation & sharing.

*We need to add Google Analytics to check site traffic on the website.

**Comment by mugabits** [comment]
[Google Analytics](https://developers.google.com/analytics/devguides/collection/analyticsjs/)  --> That's a link on how to set up Google Analytics. 

You will need to add analytics.js to the project in the _production_ codebase only to keep the repo clean, and don't forget to replace the 'UA-XXXX-Y' to the actual property you want to track. 

I have done it a few times, so let me know if you run into any issues. Also I split the original issue into two issues.

**Comment by mugabits** [comment]
I just saw that this was already done .
