### ISSUE TITLE
Feedback from LinkedIn

### ISSUE THREAD

**Issue by HiGregory** [Code-for-Miami/miami-budget#21]
I have been reaching out to the community to get feedback on our Miami As a Platform project.

Here is a link to feedback I have received : https://www.linkedin.com/grp/post/6727205-6037314167151558657?trk=groups-post-b-title

 Feedback Topics via LinkedIn Miami Tech Community
- Historic Budget Data
- Real Estate Prices (Residency)
  -Traffic Data (Ex. vehicle traffic on the highways (by hour, day, season)?)
- New Developments
- Neighborhood (Demographic Ex. Kids, Pets, Age)
- Park Budget Policy (Compare Rich & Poor Zipcodes; Tax Money Allocation)
  ![customerstalking](https://cloud.githubusercontent.com/assets/10216510/9455631/51d9a5a8-4a9b-11e5-88a9-b432d67a3a36.png)

**Comment by maurop123** [comment]
Here are the mentioned ideas we can implement:
- **Justin Gottlieb** - How about real estate prices by neighborhood/growth of residency from various other states/countries, traffic data, and new developments?
- **Patricia Kack** - Demographics per neighborhood - age range percentages, kids, and pets so you could get at a glance how young or old an area is when looking for housing.
- **Michael Neel** - How about vehicle traffic on the highways (by hour, day, season)?

I believe I've seen a UM Data Web App that takes care of the first two. I'm looking for the link.

Maybe transportation would want to take on the 3rd suggestion

**Comment by maurop123** [comment]
turned this into a trello card: https://trello.com/c/RWctTaUH/33-linkedin-feedback
