### ISSUE TITLE
Graph Sharing and Author Crediting

### ISSUE THREAD

**Issue by mugabits** [Code-for-Miami/miami-budget#30]
*We also need to implement sharing of each graph along with a line that credits the creator of the graph. The blog is a good start but having something on site might make the experience better.

![image](https://cloud.githubusercontent.com/assets/8159215/9595719/f8f8e730-5037-11e5-8f79-dc8e7fd1f4c1.png)

per @HiGregory

**Comment by maurop123** [comment]
Same as this ticket: https://github.com/Code-for-Miami/miami-budget/issues/31
