### ISSUE TITLE
Social Media Sharing 

### ISSUE THREAD

**Issue by mugabits** [Code-for-Miami/miami-budget#31]
The website needs a way for visitors to easily share the information through social media networks so that more people are aware of the budget. Perhaps even adding a Call for Action for all Miami Dade residents to become more involved in decisions made in our county.

**Comment by maurop123** [comment]
Here's one implementation idea: Upon hovering over a slice, which displays the stats for that slice, if a pie slice is clicked, the graph keeps the display and offers social sharing of the image and the stats. At least the stats.

Anyone wanna try this or offer another idea?
