### ISSUE TITLE
Submodule sunburst folder

### ISSUE THREAD

**Issue by mugabits** [Code-for-Miami/miami-budget#32]
The sunburst folder is referring another github repository that we don't have access rights to. 
You can find where it is pointing by using the terminal and going into the folder and typing  

```
git remote -v 
```

If we want that to be available in this repository, then we have a few options. 
We could create a .gitmodules file in the root directory with the following content

```
[submodule "folderName"]
  path = folderName
  url = https://github.com/[user]/[repo-name].git
```

or leave it as is - meaning no access to that repository, and then at least we know how to do it in the future. 

Thoughts?

**Comment by maurop123** [comment]
This is happening because I git cloned "https://github.com/maurop123/miami-budget" into that directory.

Fixed it thanks to this: https://github.com/maurop123/miami-budget

Changes are commited to master.
