### ISSUE TITLE
Add question polling to the site

### ISSUE THREAD

**Issue by maurop123** [Code-for-Miami/miami-budget#36]
The idea is to display a question, followed by some multiple choice answers and perhaps an "other" text input, too. The first state is displaying the question and allowing the user to click on a multiple choice answer.

The second state, after the use clicks on an answer, replaces the multiple choices with the percent that others have voted on each option. This would require that a user's vote be created in the database, and that the percent result be read and processed from the db.

Google searches such as "Meteor polling" and "Meteor vote" return some seemingly good results.

**Comment by mugabits** [comment]
Quick question: where will the questions come from? . I'm gonna start with a simple prototype, and go from there.

**Comment by mugabits** [comment]
Just checked Trello, and it seems this feature is in the test phase.

**Comment by HiGregory** [comment]
I created a prototype Miami Graph Polling website. All we need to do is create a page for it and add it on the Nav Bar (or on the main page). My suggestion is to do a redesign of the website to make it more user-friendly and easier to navigate new graph ideas.
