### ISSUE TITLE
Integrate the visualization into a website layout

### ISSUE THREAD

**Issue by maurop123** [Code-for-Miami/miami-budget#4]
The site needs a proper design. If left up to me, I'd do it with [Materialize](materializecss.com).

**Comment by ErnieAtLYD** [comment]
This template looks pretty straight forward to implement: http://materializecss.com/templates/starter-template/preview.html

**Comment by maurop123** [comment]
I agree. Aside from showing the graph, the layout has room for promoting the idea, landing-page-esque

**Comment by mugabits** [comment]
Sorry. I clicked wrong. I like material design, let me get started with this template to a general idea of what it would look like.

**Comment by maurop123** [comment]
Gregory did this. Thanks!
