### ISSUE TITLE
Budget info displayed better

### ISSUE THREAD

**Issue by maurop123** [Code-for-Miami/miami-budget#6]
The budget spreadsheet data should be displayed in a table. Preferably one that is filterable and sortable.

**Comment by maurop123** [comment]
Maybe just find a UI/UX friendly way to link/include the socrata data?

**Comment by mugabits** [comment]
Do we want interactive table? or just a read-only table?   Google's Material Design has a nice table implementation [link to table](http://www.getmdl.io/components/index.html#tables-section).
